// <auto-generated />
using System;
using BeeBilisim.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeeBilisim.Web.Migrations
{
    [DbContext(typeof(BeeDbContext))]
    [Migration("20221229140244_initial_create_new")]
    partial class initial_create_new
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BeeBilisim.Web.Models.AnasayfaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Catalog")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Email")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Entegrasyon")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Fax")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<int>("FlagTipi")
                        .HasColumnType("int");

                    b.Property<string>("GovdeMetinAciklama1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovdeMetinAciklama2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovdeMetinBasligi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Kilitli")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastupUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("NedenBizMetin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NedenBizSag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NedenBizSag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NedenBizSag3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NedenBizSag4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NedenBizSol1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NedenBizSol2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NedenBizSol3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slogan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SloganAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Special1")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special2")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special3")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool?>("İptal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AnasayfaModels");
                });

            modelBuilder.Entity("BeeBilisim.Web.Models.AnasayfaMusteriYorumlariModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Catalog")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Entegrasyon")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("FlagTipi")
                        .HasColumnType("int");

                    b.Property<bool?>("Kilitli")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastupUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("MusteriAdi")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("MusteriTitle")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special1")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special2")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special3")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Yorum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("İptal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AnasayfaMusteriYorumlariModels");
                });

            modelBuilder.Entity("BeeBilisim.Web.Models.AnaSayfaSliderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Catalog")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Entegrasyon")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("FlagTipi")
                        .HasColumnType("int");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Kilitli")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastupUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("Special1")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special2")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special3")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<bool?>("İptal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AnaSayfaSliderModels");
                });

            modelBuilder.Entity("BeeBilisim.Web.Models.BizeUlasinModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(144)
                        .HasColumnType("nvarchar(144)");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Catalog")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(144)
                        .HasColumnType("nvarchar(144)");

                    b.Property<string>("Entegrasyon")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("FlagTipi")
                        .HasColumnType("int");

                    b.Property<DateTime>("GonderilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Kilitli")
                        .HasColumnType("bit");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(144)
                        .HasColumnType("nvarchar(144)");

                    b.Property<DateTime?>("LastupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastupUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Special1")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special2")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special3")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool?>("İptal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BizeUlasinModels");
                });

            modelBuilder.Entity("BeeBilisim.Web.Models.EmailData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Captcha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Catalog")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Entegrasyon")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("FlagTipi")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GonderilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Kilitli")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastupUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Special1")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special2")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special3")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("İptal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EmailDatas");
                });

            modelBuilder.Entity("BeeBilisim.Web.Models.HakkimizdaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("BizKimizMetin1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BizKimizMetin2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Catalog")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Entegrasyon")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("FlagTipi")
                        .HasColumnType("int");

                    b.Property<string>("KendimiziTanitalim1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KendimiziTanitalim2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Kilitli")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastupUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Misyonumuz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Special1")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special2")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special3")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vizyonumuz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("İptal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HakkimizdaModels");
                });

            modelBuilder.Entity("BeeBilisim.Web.Models.HakkimizdaSliderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HakkimizdaSliderModels");
                });

            modelBuilder.Entity("BeeBilisim.Web.Models.IletisimModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdresIFrame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresMetin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Catalog")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Email")
                        .HasMaxLength(144)
                        .HasColumnType("nvarchar(144)");

                    b.Property<string>("Entegrasyon")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Fax")
                        .HasMaxLength(144)
                        .HasColumnType("nvarchar(144)");

                    b.Property<int>("FlagTipi")
                        .HasColumnType("int");

                    b.Property<bool?>("Kilitli")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastupUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Special1")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special2")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special3")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool?>("İptal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("IletisimModels");
                });

            modelBuilder.Entity("BeeBilisim.Web.Models.Kullanicilars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Catalog")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Email")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Entegrasyon")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("FlagTipi")
                        .HasColumnType("int");

                    b.Property<bool?>("Kilitli")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastupUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Sifre")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Sifre2")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Soyad")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Special1")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special2")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special3")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool?>("İptal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilars");
                });

            modelBuilder.Entity("BeeBilisim.Web.Models.ReCaptchaResult", b =>
                {
                    b.Property<string>("Captcha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ReCaptchaResults");
                });

            modelBuilder.Entity("BeeBilisim.Web.Models.ReferasanslarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Catalog")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Entegrasyon")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("FlagTipi")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Kilitli")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastupUser")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ReferansWebsite")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("Special1")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special2")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Special3")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<bool?>("İptal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ReferasanslarModels");
                });
#pragma warning restore 612, 618
        }
    }
}
